### ISSUE TITLE
WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js

### ISSUE THREAD

**Issue by stepan-techs** [ngx-rocket/cli#7]
Created project using 
npm install -g @ngx-rocket/cli
ngx new
after 
npm start
WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js
54:11-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (D:\YandexDisk\WEB\Angular\Generators\rocket cli\node_modules\webpack\lib\dependencies\ImportCo         ntextDependency.js:28:4)
    at Compilation.reportDependencyErrorsAndWarnings (D:\YandexDisk\WEB\Angular\Generators\rocket cli\node_modules\webpack\lib\Compilation.js:         677:24)
    at Compilation.finish (D:\YandexDisk\WEB\Angular\Generators\rocket cli\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (D:\YandexDisk\WEB\Angular\Generators\rocket cli\node_modules\webpack\lib\Compiler.js:512:17)
    at D:\YandexDisk\WEB\Angular\Generators\rocket cli\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\YandexDisk\WEB\Angular\Generators\rocket cli\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (D:\YandexDisk\WEB\Angular\Generators\rocket cli\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by sinedied** [comment]
See https://github.com/ngx-rocket/starter-kit/blob/cordova/ionic/docs/coding-guides/ionic.md#limitations

Nothing can be done about it unless the Ionic team decides to fix it properly. The Angular-CLI folks already pinged them concerning this, no response so far:

https://github.com/angular/angular-cli/issues/7112
https://github.com/ionic-team/ionic/issues/12285

The good news it although it's annoying, it's completely harmless as long as you don't use `@IonicPage` modules (which do not work anyway with `angular-cli`).
